### ISSUE TITLE
Timeout Issue on sample example

### ISSUE THREAD

**Issue by BalasubramanyamEvani** [hubotio/hubot-mock-adapter#18]
Hi, I followed steps in order to test hubot as mentioned in the README file but I get the following error when I run the mocha test

```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (E:\chatbots\test\test-bot\test\test.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
```

What could be the cause of this ? Any help would be appreciated.

Thanks

**Comment by joeyguerra** [comment]
More information is required to provide suggestions.
