### ISSUE TITLE
Hubot EventEmitter memory leak caused by starting and shutting down many robots

### ISSUE THREAD

**Issue by jrsquared** [hubotio/hubot-mock-adapter#2]
Since a new Robot gets created beforeEach test, and robot.shutdown() doesn't clean up EventEmitters, if I create a lot of tests, I get:

`(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.`

It looks like robot adds an uncaughtexception listener to process that it doesn't clean up on shutdown.

I plan on adding tests, so setting max listeners doesn't seem like a good fix.  Any recommended way to clean up?

**Comment by patrickbcullen** [comment]
I have a partial workaround for this error. If you change your robot to be constructed once per test file and call removeAllListeners in the afterEach method, it gets rid of this error.

``` coffescript
before (done) ->
    # Create new robot, without http, using mock adapter
    robot = new Robot null, "mock-adapter", false

    robot.adapter.on "connected", ->

      # load the module under test and configure it for the
      # robot. This is in place of external-scripts
      require("../src/mymodule")(robot)
      adapter = robot.adapter

    robot.run()

    done()

  after ->
    robot.shutdown()

  afterEach ->
    robot.adapter.removeAllListeners()
```

**Comment by joeyguerra** [comment]
Stale.
