### ISSUE TITLE
Some files have names -- but I'm having trouble guessing path and name

### ISSUE THREAD

**Issue by chickenandpork** [hubotio/hubot-mock-adapter#22]
Hi;  Your examples would be more approachable if there was a hint as to whether each were in a `./src`, `./scripts/src`, `./src/scripts`, `./src/test`, `./test` directory, and a `.coffee`, `.js`, either, both, does-not-matter, etc.  Finding a difficult time following the walk-through and randomly arrive at the same directory structure as you have, or see why it's not working.

... even if you don't want to pin a reader down to a certain directory structure, can you give a noob a hint as to what you had, that actually works?  That would make your examples actionable.

**Comment by joeyguerra** [comment]
Can you elaborate? What's the "each" referring to in the question?

**Comment by chickenandpork** [comment]
sorry.. thinking back .. this was "each file".  I remember reading through your examples, and appreciating your effort, but feeling really frustrated with "what directory is this?  which is that?"

Ultimately, I got GRPC working in coffeescript and did most of the logic in Go instead.

I feel really bad -- and a bit stupid -- that I couldn't get it cleanly going natively.  I wasn't able to fully appreciate all the work you did to share your knowledge :-(

Thanks for making the effort to share, though.  It's often thankless volunteer work.

**Comment by joeyguerra** [comment]
I see. Thanks for replying. My current thought is to not use this repo, just create an adapter to use for testing.

If you've already moved on to another solution, I'll close this issue.
